### ISSUE TITLE
Can't switch bodies when Campanion is installed

### ISSUE THREAD

**Issue by ogpw** [Kira-NT/sync-fabric#12]
Not sure ~~if this is an issue more to do~~ if the issue is caused by Campanion or your mod but, seen as the issue ~~is to do with your mod~~ occurs within your mod when the aforementioned is installed, I thought I'd raise the issue here.

When Campanion v2.0.0-beta.1 for 1.17.1 is installed alongside Sync mc1.17.x-1.2, you can't switch between clones. You will walk into a storage unit, select another clone, and the camera will go out of the body and do half of the "switching" animation where the camera flies into the sky. However, the camera will remain in the sky and will not come back down and you will be forced to leave and re-enter the game. When re-entering the game, you are back in the normal body (i.e. you haven't changed bodies) as if you had walked in the storage unit and had clicked the cross to exit the clone selection menu.

Edit 25/09/2021: Fixed poor phrasing.

**Comment by Kira-NT** [comment]
Thank you for the report, will investigate this tomorrow

**Comment by Kira-NT** [comment]
Technically, the issue was caused by the Campanion mod *(folks don't know what the null check is)*, but considering that there may be a lot of mods with the same problem in the wild, I've rearranged some things, so thank you once again for letting me know!

P.S. - I don't know when I will publish a new release, but you can grab the latest dev build here: https://github.com/Kir-Antipov/sync-fabric/actions/runs/1298451883
