### ISSUE TITLE
Hardcore Mode on multiplayer server doesn't drop you into one of your shells

### ISSUE THREAD

**Issue by Mrod1598** [Kira-NT/sync-fabric#16]
I've tried testing this out on a multiplayer server and it seems that it doesn't drop you into one of your shells when you die. We tested this with multiple different players and all of them weren't dropped into a fully built shell. We can swap between shells easy enough, but doesn't want to work on death.

**Comment by Kira-NT** [comment]
Did you switch to a built shell before dying?

**Comment by Mrod1598** [comment]
yes

**Comment by Kira-NT** [comment]
I didn't test hardcore servers before, but I did test survival ones and there were no problems at all

Could you use the latest [dev build from GitHub Actions](https://github.com/Kir-Antipov/sync-fabric/actions/runs/1421236816), please? Because I cannot reproduce the issue. Also, make sure to switch to a new shell before dying, since when your original body dies, you'll die too
