### ISSUE TITLE
[Feature Request] Shell construction Doesn't Kill players

### ISSUE THREAD

**Issue by Desher02** [Kira-NT/sync-fabric#17]
### Problem

Currently, starting the construction of a shell kills the player unless they have a totem of undying or an enchanted golden apple, and that's not how the old versions of this mod worked.

### Feature

Bring the damage down to a heart or so, that way people in hardcore can reliably use the shells to prolong their play.

### Other Solutions

Create a way to start the construction in a safer manner. this could involve a syringe to extract your DNA or something like that so it doesn't take your life instead of a small bit of life.

### Additional Information

Just as a secondary suggestion, making the constructor compatible with other mods for their energy, that would be great!

**Comment by Kira-NT** [comment]
> Currently, starting the construction of a shell kills the player unless they have a totem of undying or an enchanted golden apple, and that's not how the old versions of this mod worked.

Yup, I know. As it stated in the README, the mod is not a port of the original project, it's a reimplementation, therefore I'm free to tweak some ideas to match my own vision

> Bring the damage down to a heart or so, that way people in hardcore can reliably use the shells to prolong their play

I don't like this solution, to be quite frankly honest with you, because it's already a part of the mod's agenda - *"In order to create a shell with full health, the constructor must absorb 20HP"*
"Eye for an eye" kind of thing.

But I can add an option to the upcoming config update, so you can change this behavior yourself

> Create a way to start the construction in a safer manner. this could involve a syringe to extract your DNA or something like that so it doesn't take your life instead of a small bit of life.

Actually, I have something like this in mind in order to sort out #14 

> Just as a secondary suggestion, making the constructor compatible with other mods for their energy, that would be great!

If I understand you correctly, this is already a thing. The mod is compatible with popular tech mods
