### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by PhlompfDev** [Kira-NT/sync-fabric#21]
### What happened?

Shells disappear when changing dimensions, not sure whether it's when you enter a new one, or leave it. 

Update: I believe the shells disappear due to the fact that all pigs stand up when I unload the chunk, causing the storage unit to lose power.

Update #2: Problem solved, by force loading the chunk, storage units do not lose power, thus the shells continue living. 
The solution I suggest you add is maybe allowing more time without power before the shells die, or maybe have them chunk load themselves.

### Version

sync-mc1.18-3.1

### Minecraft Version

fabric-loader-0.12.12-1.18.1

### Fabric API Version

fabric-api-0.45.0+1.18

### Installation Source

CurseForge

### Logs

```shell
Was unable to find the log for the exact time, it was in a singleplayer world but I can't find the correct one as it doesn't seem to exist. Sorry for the inconvenience.
```

### Other Mods

```shell

**Tested without any external mods, issue does not persist.**

Mods included in test above are: 

 - cloth-config-6.1.48-fabric
 - fabric-api-0.45.0+1.18
 - sync-mc1.18-3.1

 [Mods In Singleplayer world when issue occured]

**

> Chest Cavity
> Architectury
> Cloth Config
> Health Overlay
> Icarus
> Mining Dimensions Fabric
> Mod Menu
> Mostructures
> MouseTweaks 
> Quartz Elevator
> REI
> Smart Recipes
> Sodium fabric [alpha build] <---- (Maybe a cause??)
> Trinkets
> WTHIT
> Xaeros Minimap, and Worldmap

**
```

**Comment by Kira-NT** [comment]
There's a config option that does exactly what you want - `shellStorageMaxUnpoweredLifespan`. You can change it manually in the config file *(./config/sync.json)*, or via ModMenu.

Let me know, which value solves the issue, and I may set it as default one.

**Comment by Kira-NT** [comment]
I'm closing this one, because this is not really an issue, it's just how things work - if a shell container loses power, its shell will die.

Treadmills are not a reliable power source, they are meant to be fun, no more, no less. Like, I would not entrust production of energy for cooling a nuclear reactor or for a life support system to a pig running on a treadmill. If you want to deal with well known vanilla mechanics like chunk loading/unloading, it's up to you, but the mod itself has nothing to do with this.

If you will find a value for the `shellStorageMaxUnpoweredLifespan` property, that will make things reliable, please, let me know, because I may set it as default one. Otherwise, you still have a redstone block and power sources from tech mods as an option.
