### ISSUE TITLE
Death in Aether Reborn with shell doesn't transfer player back to original.

### ISSUE THREAD

**Issue by PseudoDistant** [Kira-NT/sync-fabric#3]
Title.

Workaround: Move from the shell you're now stuck in to another shell, and die.
(Just dying in any dimension after dying in the Aether will just kill you normally.)

**Comment by Kira-NT** [comment]
Hm. Well, what actually happens when you die as a shell in the Aether dimension?

**Comment by PseudoDistant** [comment]
> Hm. Well, what actually happens when you die as a shell in the Aether dimension?

I die as though I'm not a shell.

Basically I die normally, and respawn in the Overworld.
Dying after this point just kills me normally, and gives me the respawn prompt.
If I then put the shell I'm in in a shell storage block(s), and move to another shell, then die, I go back to the original body.

**Comment by Kira-NT** [comment]
Got it, thank you for the clarification! I think, I know what can cause the issue. Will investigate into this soon

**Comment by Kira-NT** [comment]
The problem was `Aether` doesn't use the `moveToWorld` method to teleport players across dimensions, which is different to vanilla behavior I relied on. That's why your shells weren't synchronized after moving to/out of the Aether dimension via portal/falling from the sky

Anyway, fixed in the latest dev build. Thanks for reporting this one!

**Comment by PseudoDistant** [comment]
You're welcome. :>
And thank you. :D
