### ISSUE TITLE
[Compatibility] 

### ISSUE THREAD

**Issue by lomovoyPlayer** [Kira-NT/sync-fabric#32]
### Related Project(s)

Traveler's Backpack
a similar problem with chest cavity

### Problem

the put-on backpack is one for all shells

### Feature

I don't know how, but I think it's already clear that it's necessary for the backpack to be personalized for each shell

### Justification

I don't know, intuition

### Additional Information

a similar problem with chest cavity

**Comment by Kira-NT** [comment]
> I don't know, intuition

It's not a very good reason to burden an infinite amount of unpaid work on someone's shoulders, don't ya think? :)

I'm not gonna implement compatibility with some random mods without strongly defined APIs that were not created to be used like that. Therefore, I will leave this to developers of the said mods, because this project **has** an API that **was** designed to be used like that, so, better luck with them :)
