### ISSUE TITLE
Shell disappeared from Powered Storage, can still se the Shell in the radial menue but cant switch to it

### ISSUE THREAD

**Issue by SuperHerp** [Kira-NT/sync-fabric#4]
I made a shellstorage container in the end, swapped to a shell in the overworld, when trying to switch back my shell in the end still shows up, but when i try to switch to it i just stay in my current shell. When i visited the end where i placed the shell storage, it seems to be empty, even tho there is an active power source (redstone torch). also the shell appears to be alive in the radial menue so idk what to do.
i tried to power the storage down in order to let the shell die so i can get my items back but that didnt work either. 
Are my items stuck in limbo? is there a way to resolve this?

**Comment by Kira-NT** [comment]
Oh... I'm very sorry that this happened! Could you provide me with all available information on this *(e.g., Minecraft version, coords of you shell storages, your power setup and everything you consider important)*, so I can try to recreate the problem, understand where its roots lie, and prevent it from happening in the future?

> Are my items stuck in limbo? is there a way to resolve this?

Technically, the shell you're talking about does not exist *(for some weird reason)*, everything you have is just an information about it, which you can see in the radial menu. Thankfully, this information can be used to repair your missing shell, so don't worry, your items are not completely gone!

I have a `/sync fix @a` command in my TODO list for a while now, because it's impossible to keep everything in *sync* in all edge cases.

![Ironic, isn't it?](https://user-images.githubusercontent.com/40232067/132049831-5aec81c5-d2b8-4a1e-9add-cc2a67b2950a.png)

So, I'm aware that sometimes "ghost"-shells can infiltrate player's radial menu *(e.g., if server stopped during the sync process)*, but, to be quite frankly honest with you, I didn't think about your scenario, where "ghost"-shell should actually exist. Therefore, it's a good thing that I still haven't implemented the command without knowing about this.

I wanted to do this a little bit later, but it seems like an emergency. Hopefully tomorrow you can see your shell and your items again :)

P.S. - please, don't remove the shell storage that misses the shell. If you did, just put it back where it were

**Comment by SuperHerp** [comment]
Minecraft Ver: fabric loader 0.11.6 1.17.1
Storages (all powered with redstone torch):
Overworld: 
1.: 652 54 508
2.: 497 40 695
Nether:
1.: 82 57 76
End:
1.: 268 3 -5

not rly an emergency, its just a single player world but i rly would like those items back since it was my complete netherite gear lol

edit: no power mods or dimension mods or anything like it

**Comment by Kira-NT** [comment]
Have just made a command that can help you.

```cmd
/sync ghostshells repair YourNickname x y z
```
 - `YourNickname` is... your nickname ¯\\_(ツ)_/¯
 - `x y z` are coords of the missing shell

P.S. - I need to do a few more things before releasing a new version, so you can grab the latest dev build [here](https://github.com/Kir-Antipov/sync-fabric/actions/runs/1201550915).
P.P.S. - Please, let me know, how it went :)

**Comment by Kira-NT** [comment]
Leaving this open, since I haven't had time to try to reproduce the issue and *maybe* find a way to mitigate the problem yet

**Comment by SuperHerp** [comment]
Nice the command fixed it for me.
thanks for the quick fix!

**Comment by Kira-NT** [comment]
Cool! Thank you for letting me know :)

> thanks for the quick fix!

You're welcome! Sorry for the inconvenience once again

**Comment by Kira-NT** [comment]
Took a deeper look at the situation. It seems that chunk with the shell storage was unloaded mid-tick. Sadly, there's literally nothing I can do about this - this is an emergency scenario just like a server crash. At least players now have a tool to mitigate the problem in rare cases when such a thing happens
