### ISSUE TITLE
[Feature Request] List of energy options

### ISSUE THREAD

**Issue by ashyashton** [Kira-NT/sync-fabric#41]
### Problem

I understand that there are no plans to change the fact that pigs are an unreliable source of power, and that chunk unloading/cross-dimensional travel is outside the scope of this mod. This, along with the advice to just use an energy mod, can be found in issue #21 in the last reply. There doesn't seem to be an obvious way of knowing what tech mods are compatible, though.

### Feature

I believe the solution to this problem is to include a section on the mod's description page that lists what energy mods will work to power this mod, beyond a simple "popular tech mods" description which is only useful if you know what tech mods are popular. Without such a list, the only option for users would be to try every energy mod and test which ones do and don't work. This seems unnecessary, as I'm sure you as the mod author are already aware of what mods would or would not work.

### Other Solutions

It might also help to change the instructions in the description as well. The "how to play" section _only_ lists pthe treadmill as an option for construction, and only redstone or the treadmill for storage. The idea of using energy mods isn't brought up until the "notes" section, and then it's only a fraction of one subheaded bullet point, making it incredibly easy to miss. 

### Additional Information

I am not asking to add compatibility with other mods. I know that that's on other mod authors as you've provided the API for them to do so, and it's much less work for everyone. I'm just looking for an easy way to know which ones _are_ already compatible.

**Comment by Kira-NT** [comment]
As a side note, I greatly appreciate the fact that you conducted some research before opening the issue and reviewed my previous responses and other issues.

Now, onto the matter at hand. You know, it would be actually kinda funny if I had the full list of compatible tech mods and just chose to keep it a secret. However, your assumption falls a bit short in this regard. I didn't use the wording I did in order to intentionally maintain vagueness, but rather because I myself have no idea which tech mods are compatible with `sync-fabric` xD

The public API exposed by this mod primarily focuses on manipulating shells, as that's the core functionality it adds to the game, rather than dealing with the concept of energy. To handle energy, `sync-fabric` relies on an existing API, namely `teamreborn:energy`, which was created and is used by the TechReborn team. However, this doesn't mean that Sync (Fabric) is exclusively compatible with TechReborn. Other tech mods either use `teamreborn:energy` under the hood, incorporate compatibility layers for it, or at least it's possible to find third-party compatibility mods for that. As a result, determining which tech mods are compatible with `sync-fabric` is quite a challenge. Even if I were to invest time in researching this, it is subject to change - someone could replace `teamreborn:energy` with their own custom solution, or vice versa.

Nevertheless, I agree that I can make it easier for players by adding something to the README along the lines of "compatible with TechReborn and other tech mods that are compatible with TechReborn itself". At the very least, this would reflect the full extent of my knowledge on this topic

**Comment by ashyashton** [comment]
Y'know that's fair enough! And to be clear, I didn't actually think you had, like, a list or anything, so much as I just kind of assumed it was one of those things that someone involved in the project would be able to figure out easily while some dummy like me wouldn't get it at all. I was moreso assuming that you hadn't bothered to take the time to make a proper list. You're absolutely right though; it would be REALLY funny if you straight up had the list and just kept it quiet to be vague!
